[build]
  publish = "dist/spa"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

# Headers for HTTPS and camera access
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=self, microphone=self"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Special headers for AR pages
[[headers]]
  for = "/ar-experience"
  [headers.values]
    Permissions-Policy = "camera=self, microphone=self, accelerometer=self, gyroscope=self"
    
# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
